complete -c riptag -l compilation -d "Mark as compilation album"
complete -c riptag -l compilation=false -d "Explicitly not a compilation"
complete -c riptag -l year -d "Set the same year on every track (--year=YYYY)"
complete -c riptag -l resume -d "Resume a failed session (--resume=<id>, implies --local)"
complete -c riptag -l replaces -d "Re-download guard: library-relative path (--replaces=PATH)"
complete -c riptag -l local -d "Run streamrip locally instead of on NAS"
complete -c riptag -l help -s h -d "Show usage"
