####################
# Global Options
####################

library: /Volumes/AlecsVault/Music/Beets/musiclibrary.db
directory: /Volumes/AlecsVault/Music/Media.localized/Music
plugins:
  - bpmanalyser
  - chroma
  - discogs
  - deezer
  - edit
  - embedart
  - fetchart
  - fromfilename
  - ftintitle
  - hook
  - info
  - lastgenre
  - missing
  - scrub
  - zero

# .gitignore'd file with various API keys
include:
  - secrets.yaml

import:
  incremental: yes
  move: yes
  log: beets.log

match:
  strong_rec_thresh: 0.25
  max_rec:
    missing_tracks: strong
    unmatched_tracks: strong
  distance_weights:
    missing_tracks: 0.15
  preferred:
    countries: ['US', 'GB|UK', 'XW']
    media: ['Digital Media|File', 'Digital Media', 'CD']
    original_year: yes

####################
# Plugin Options
####################

chroma:
  auto: no

fetchart:
  enforce_ratio: yes
  minwidth: 800
  sources:
    - coverart
    - itunes
    - amazon
    - albumart
    - fanarttv
    - google
    - wikipedia
    - lastfm
    - filesystem

ftintitle:
  format: (feat. {0})

hook:
  hooks:
    - event: after_write
      command: osascript /Volumes/AlecsVault/Music/Beets/MusicRefresh.scpt "{item.path}"

lastgenre:
  whitelist: ~/.config/beets/genres.txt
  canonical: ~/.config/beets/genres-tree.yaml
  fallback: 'Unknown'
  source: artist

zero:
  fields: albumartist_sort artist_sort comments composer composer_sort
  comments: (?!running_include|running_exclude)(^.*$)
  update_database: true
