####################
# Global Options
####################

library: /Users/alec/.beets/musiclibrary.db
directory: /Users/alec/.beets/_staging
plugins:
  - chroma
  - discogs
  - deezer
  - edit
  - embedart
  - fetchart
  - fromfilename
  - ftintitle
  - info
  - lastgenre
  - missing
  - scrub
  - zero

# .gitignore'd file with various API keys
include:
  - secrets.yaml

import:
  copy: no
  move: yes
  incremental: yes
  write: yes
  languages: en
  autotag: yes
  log: /Users/alec/.beets/beets.log

match:
  strong_rec_thresh: 0.25
  max_rec:
    missing_tracks: strong
    unmatched_tracks: strong
  distance_weights:
    missing_tracks: 0.15
  preferred:
    countries: ['US', 'GB|UK', 'XW']
    media: ['Digital Media|File', 'Digital Media', 'CD']
    original_year: yes

####################
# Plugin Options
####################

chroma:
  auto: no

fetchart:
  enforce_ratio: yes
  minwidth: 800
  sources:
    - coverart
    - itunes
    - amazon
    - albumart
    - fanarttv
    - google
    - wikipedia
    - lastfm
    - filesystem

ftintitle:
  format: (feat. {0})

lastgenre:
  whitelist: /Users/alec/.config/beets/genres.txt
  canonical: /Users/alec/.config/beets/genres-tree.yaml
  fallback: 'Unknown'
  source: artist

scrub:
  auto: no

zero:
  fields: acoustid_fingerprint acoustid_id albumartist_sort albumdisambig albumtype albumtypes artist_sort comments composer composer_sort lyrics mb_albumartistid mb_albumartistids mb_albumid mb_artistid mb_artistids mb_releasetrackid mb_releasegroupid mb_trackid media
  comments: (?!running_include|running_exclude)(^.*$)
  update_database: true
