####################
# Global Options
####################

library: ~/Music/Beets/musiclibrary.db
directory: ~/Music/Music/Media.localized/Music
plugins:
  - acousticbrainz
  - bpmanalyser
  - chroma
  - discogs
  - deezer
  - edit
  - embedart
  - fetchart
  - fromfilename
  - ftintitle
  - goingrunning
  - hook
  - info
  - lastgenre
  - missing
  - scrub
  - zero

# .gitignore'd file with various API keys
include:
  - secrets.yaml

import:
  move: yes
  log: beets.log
match:
  strong_rec_thresh: 0.20
  # Enable below line if doing a full library import
  # strong_rec_thresh: 0.30
  max_rec:
    missing_tracks: strong
  distance_weights:
    missing_tracks: 0.90
    # Enable below line if doing a full library import
    # missing_tracks: 0.15
  preferred:
    countries: ['US', 'GB|UK', 'XW']
    media: ['Digital Media|File', 'Digital Media', 'CD']
    original_year: yes

####################
# Plugin Options
####################

acousticbrainz:
  tags: [bpm]

chroma:
  auto: no

fetchart:
  enforce_ratio: yes
  minwidth: 800
  sources:
    - coverart
    - itunes
    - amazon
    - albumart
    - fanarttv
    - google
    - wikipedia
    - lastfm
    - filesystem

ftintitle:
  format: (feat. {0})

goingrunning:
  targets:
    MPD1:
      device_root: ~/Music/Beets/Playlists/
      clean_target: no
      generate_playlist: yes
      copy_files: no
  trainings:
    60min:
      query:
        bpm: 160..180
        genre:
          - Electronic
          - Hip-Hop
          - Mashup
          - Pop
          - R&B
          - Soundtrack
      ordering:
        bpm: 100
      use_flavours: []
      duration: 60
      target: MPD1

hook:
  hooks:
    - event: after_write
      command: osascript /Users/alec/Music/Beets/MusicRefresh.scpt "{item.path}"

lastgenre:
  whitelist: ~/.config/beets/genres.txt
  canonical: ~/.config/beets/genres-tree.yaml
  fallback: 'Unknown'
  source: artist

zero:
  fields: albumartist_sort artist_sort comments composer composer_sort
  composer: (?!running_include|running_exclude)(^.*$)
  update_database: true
