matches:
  # Date expansion
  - trigger: ":today"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%Y-%m-%d"

  # Time expansion
  - trigger: ":time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  # console.log(<cursor>)
  - trigger: :log
    replace: console.log($|$)

  # Example of a shell command
  # - trigger: ":shell"
  #   replace: "{{output}}"
  #   vars:
  #     - name: output
  #       type: shell
  #       params:
  #         cmd: "echo 'Hello from your shell'"
