auto-password-input:
  enable: true # optional, defaults to false
  #account_name: ... # optional, defaults to $USER else $whoami

blocks:
  - days: [Mon, Tue, Wed, Thu, Fri]
    times: [[5:00, 17:00]]
# - days: [Thu]
#   times: [[21:00, 08:00]] # This will block from Thursday 21:00 until Friday 08:00
# - days: [All]
#   times: [[8:00, 9:00]]
# Explicitly defined weekdays override 'All'- eg Monday will not contain the 8:00 -> 9:00 block

paths:
  #self-control: ... # optional, defaults to /Applications/SelfControl.app/Contents/MacOS/org.eyebeam.SelfControl
  #launch-agents: ... # optional, defaults to ~/Library/LaunchAgents/
