#!/usr/bin/env bash
#
# Injects secrets into settings.template.json (JSONC, tracked) using 1Password CLI
# and saves to settings.json (gitignored, symlinked by stow).
#
set -e

# Outputs hold resolved secrets; keep them (and the .tmp staging file) 0600.
umask 077

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ZED_DIR="$DOTFILES/stow/zed/.config/zed"
TEMPLATE="$ZED_DIR/settings.template.jsonc"
OUT="$ZED_DIR/settings.json"

# Clean up the intermediate .tmp file if we're killed between the sed
# pipeline and the atomic mv. Without this, a SIGINT mid-build leaves a
# file with fully-resolved 1Password secrets sitting on disk indefinitely.
TMP=""
cleanup() {
    if [[ -n "$TMP" && -f "$TMP" ]]; then
        rm -f "$TMP"
    fi
}
trap cleanup EXIT

if [ ! -f "$TEMPLATE" ]; then
  echo "Error: $TEMPLATE not found"
  exit 1
fi

if ! command -v op >/dev/null 2>&1; then
  echo "Error: 1Password CLI (op) is not installed." >&2
  echo "  Install with: brew install --cask 1password-cli" >&2
  exit 1
fi
# `op vault list` rather than `op whoami`: with 1Password app integration
# enabled, `op whoami` reports "not signed in" even when data commands work.
if ! op vault list >/dev/null 2>&1; then
  echo "Error: 1Password CLI can't read your vaults." >&2
  echo "  Enable 1Password > Settings > Developer > 'Integrate with 1Password CLI', then unlock the app." >&2
  echo "  Or, for a temporary session: eval \$(op signin)" >&2
  exit 1
fi

echo "Injecting secrets using 1Password CLI..."
op inject -f -i "$TEMPLATE" -o "$OUT"

# Fail loudly if any op:// reference remains unresolved. Silent fallthrough
# here previously left Zed reading literal "op://Vault/Item/Field" strings.
if grep -q 'op://' "$OUT"; then
  echo "Error: unresolved op:// references remain in $OUT" >&2
  grep -n 'op://' "$OUT" >&2
  rm -f "$OUT"
  exit 1
fi

# Replace ${HOME} placeholder with the actual home directory path
# and prepend a warning comment about editing the generated file.
TMP="${OUT}.tmp"
{
  echo "// DO NOT EDIT THIS FILE DIRECTLY!"
  echo "// This file is auto-generated from settings.template.json."
  echo "// Any changes made here will be overwritten by the build script."
  sed "s|\${HOME}|${HOME}|g" "$OUT"
} >"$TMP" && mv "$TMP" "$OUT"
TMP=""

echo "Successfully built Zed config: $OUT"
