#!/usr/bin/env bash
#
# Injects secrets into settings.template.json (JSONC, tracked) using 1Password CLI
# and saves to settings.json (gitignored, symlinked by stow).
#
set -e

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ZED_DIR="$DOTFILES/stow/zed/.config/zed"
TEMPLATE="$ZED_DIR/settings.template.jsonc"
OUT="$ZED_DIR/settings.json"

if [ ! -f "$TEMPLATE" ]; then
  echo "Error: $TEMPLATE not found"
  exit 1
fi

if ! command -v op >/dev/null 2>&1; then
  echo "Error: 1Password CLI (op) is not installed." >&2
  echo "  Install with: brew install --cask 1password-cli" >&2
  exit 1
fi
if ! op whoami >/dev/null 2>&1; then
  echo "Error: 1Password CLI is not signed in." >&2
  echo "  Sign in with: eval \$(op signin)" >&2
  echo "  Or enable Touch ID/SSH agent in 1Password's Developer settings." >&2
  exit 1
fi

echo "Injecting secrets using 1Password CLI..."
op inject -f -i "$TEMPLATE" -o "$OUT"

# Fail loudly if any op:// reference remains unresolved. Silent fallthrough
# here previously left Zed reading literal "op://Vault/Item/Field" strings.
if grep -q 'op://' "$OUT"; then
  echo "Error: unresolved op:// references remain in $OUT" >&2
  grep -n 'op://' "$OUT" >&2
  rm -f "$OUT"
  exit 1
fi

# Replace ${HOME} placeholder with the actual home directory path
# and prepend a warning comment about editing the generated file.
{
  echo "// DO NOT EDIT THIS FILE DIRECTLY!"
  echo "// This file is auto-generated from settings.template.json."
  echo "// Any changes made here will be overwritten by the build script."
  sed "s|\${HOME}|${HOME}|g" "$OUT"
} >"${OUT}.tmp" && mv "${OUT}.tmp" "$OUT"

echo "Successfully built Zed config: $OUT"
