#!/usr/bin/env bash
#
# Fetches the Context7 API key from 1Password and writes a gitignored fish
# conf.d snippet (symlinked into ~/.config/fish/conf.d/ by stow) that exports
# CONTEXT7_API_KEY. fish sources conf.d on shell start, so any `claude` (and
# the stdio MCP servers it spawns) launched from the terminal inherits the
# key. @upstash/context7-mcp reads CONTEXT7_API_KEY natively, which lifts the
# anonymous rate limit.
#
# Single-value secret, so this uses `op read` and writes the file directly
# rather than the `op inject` template flow used by build-zed/build-streamrip:
# a `*.template.fish` living in conf.d would itself be auto-sourced by fish.
#
set -e

# Outputs hold resolved secrets; keep them (and the .tmp staging file) 0600.
umask 077

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$DOTFILES/stow/fish/.config/fish/conf.d/context7.fish"
OP_REF="op://Private/25nqmf6ljgb6ry5aowcegxabpa/credential"

# Remove the intermediate file if we're killed mid-write so a truncated file
# holding a half-written secret can't linger on disk.
TMP=""
cleanup() {
    if [[ -n "$TMP" && -f "$TMP" ]]; then
        rm -f "$TMP"
    fi
}
trap cleanup EXIT

if ! command -v op >/dev/null 2>&1; then
  echo "Error: 1Password CLI (op) is not installed." >&2
  echo "  Install with: brew install --cask 1password-cli" >&2
  exit 1
fi
# `op vault list` rather than `op whoami`: with 1Password app integration
# enabled, `op whoami` reports "not signed in" even when data commands work.
if ! op vault list >/dev/null 2>&1; then
  echo "Error: 1Password CLI can't read your vaults." >&2
  echo "  Enable 1Password > Settings > Developer > 'Integrate with 1Password CLI', then unlock the app." >&2
  echo "  Or, for a temporary session: eval \$(op signin)" >&2
  exit 1
fi

echo "Fetching Context7 API key from 1Password..."
KEY="$(op read "$OP_REF")"
if [ -z "$KEY" ]; then
  echo "Error: Context7 key at $OP_REF resolved empty." >&2
  exit 1
fi

TMP="${OUT}.tmp"
{
  echo "# DO NOT EDIT THIS FILE DIRECTLY!"
  echo "# Auto-generated by scripts/build-context7-config.sh from 1Password ($OP_REF)."
  echo "# Exports the Context7 API key so terminal-launched Claude Code (and the"
  echo "# stdio MCP servers it spawns) authenticate instead of using the anonymous"
  echo "# rate limit. @upstash/context7-mcp reads CONTEXT7_API_KEY natively."
  echo "set -gx CONTEXT7_API_KEY '$KEY'"
} >"$TMP" && mv "$TMP" "$OUT"
TMP=""

echo "Successfully built Context7 fish config: $OUT"
