# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

matches:
  # Simple text replacement
  - trigger: ':espanso'
    replace: 'Hi there!'

  # princeum ipsum
  - trigger: ':princeum'
    replace: >
      Now, this is a story all about how
      My life got flipped-turned upside down
      And I'd like to take a minute
      Just sit right there
      I'll tell you how I became the prince of a town called Bel Air.

  # Dates
  - trigger: ':today'
    replace: '{{today}}'
    vars:
      - name: today
        type: date
        params:
          format: '%F'

  # Shell commands
  - trigger: ':shell'
    replace: '{{output}}'
    vars:
      - name: output
        type: shell
        params:
          cmd: 'echo Hello from your shell'

  # Cypress context
  - trigger: ':context'
    replace: "context('$|$', () => {});"

  # Thumbs up
  - trigger: ':plus1'
    replace: '👍'

  # console.log(|)
  - trigger: ':log'
    replace: 'console.log($|$);'

  # up arrow
  - trigger: ':uar'
    replace: '↑'

  # right arrow
  - trigger: ':rar'
    replace: '→'

  # down arrow
  - trigger: ':dar'
    replace: '↓'

  # left arrow
  - trigger: ':lar'
    replace: '←'
